version: '3.3'
services:
  #application:
   # build: .
    #ports:
     # - 8888:8888
    #restart: always
    #links:
     # - db:database

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'futureh'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
