version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:  
      MYSQL_DATABASE: 'futureh'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  #application:
    #build: .
    #ports:
      #- 8080:8080
    #restart: always
    #depends_on: ["mysql"]

  