version: "3.8"

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      DB_USER: user
      DB_PASS: password
      DB_URL: jdbc:mysql://database:3306/futureh

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: futureh
    restart: always

